# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-10 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 17, 33, 54, 694352, tzinfo=utc)),
        ),
    ]
